const register = require('./register');
const Router = require('express').Router;
const createDoctor = require('./create.doctor');
const listDepartments = require('./list.departments');
const listDoctors = require('./list.doctors');
const otpSend = require('./otp.send');
const otpVerify = require('./otp.verify');
const createDutySchedule = require('./create.duty-schedule');
const saveSchedule = require('./save.schedule');
const getUpcomingSchedule = require('./get.upcoming-schedule');
const dashboard = require('./dashboard');
const listTodayShifts = require('./list.today-shifts');
const doctorDashboard = require('./doctor.dashboard');
const authentication = require('../../middlewares/authentication');
const doctorTokenMarkAs = require('./doctor.token.mark.as');
const hospitalRouter = Router();

hospitalRouter.get('/dashboard', authentication, dashboard);
hospitalRouter.post('/register', register);
hospitalRouter.post('/doctor', createDoctor);
hospitalRouter.get('/departments', authentication, listDepartments);
hospitalRouter.post('/schedule/duty', authentication, createDutySchedule);
hospitalRouter.post('/schedule/save', authentication, saveSchedule);
hospitalRouter.get('/schedule/upcoming', authentication, getUpcomingSchedule);
hospitalRouter.get('/schedule/today', authentication, listTodayShifts);
hospitalRouter.post('/otp/send', otpSend);
hospitalRouter.post('/otp/verify', otpVerify);
hospitalRouter.post('/doctor', authentication, createDoctor);
hospitalRouter.get('/doctors', authentication, listDoctors);
hospitalRouter.get('/doctors/dashboard', authentication, doctorDashboard);
hospitalRouter.post('/doctors/token/markas', authentication, doctorTokenMarkAs);
module.exports = hospitalRouter;
